/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Vmal0WhereInput } from "./Vmal0WhereInput";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";

@InputType()
class Vmal0ListRelationFilter {
  @ApiProperty({
    required: false,
    type: () => Vmal0WhereInput,
  })
  @ValidateNested()
  @Type(() => Vmal0WhereInput)
  @IsOptional()
  @Field(() => Vmal0WhereInput, {
    nullable: true,
  })
  every?: Vmal0WhereInput;

  @ApiProperty({
    required: false,
    type: () => Vmal0WhereInput,
  })
  @ValidateNested()
  @Type(() => Vmal0WhereInput)
  @IsOptional()
  @Field(() => Vmal0WhereInput, {
    nullable: true,
  })
  some?: Vmal0WhereInput;

  @ApiProperty({
    required: false,
    type: () => Vmal0WhereInput,
  })
  @ValidateNested()
  @Type(() => Vmal0WhereInput)
  @IsOptional()
  @Field(() => Vmal0WhereInput, {
    nullable: true,
  })
  none?: Vmal0WhereInput;
}
export { Vmal0ListRelationFilter as Vmal0ListRelationFilter };
