/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Vmal0WhereInput } from "./Vmal0WhereInput";
import { IsOptional, ValidateNested, IsInt } from "class-validator";
import { Type } from "class-transformer";
import { Vmal0OrderByInput } from "./Vmal0OrderByInput";

@ArgsType()
class Vmal0FindManyArgs {
  @ApiProperty({
    required: false,
    type: () => Vmal0WhereInput,
  })
  @IsOptional()
  @ValidateNested()
  @Field(() => Vmal0WhereInput, { nullable: true })
  @Type(() => Vmal0WhereInput)
  where?: Vmal0WhereInput;

  @ApiProperty({
    required: false,
    type: [Vmal0OrderByInput],
  })
  @IsOptional()
  @ValidateNested({ each: true })
  @Field(() => [Vmal0OrderByInput], { nullable: true })
  @Type(() => Vmal0OrderByInput)
  orderBy?: Array<Vmal0OrderByInput>;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsOptional()
  @IsInt()
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  skip?: number;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsOptional()
  @IsInt()
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  take?: number;
}

export { Vmal0FindManyArgs as Vmal0FindManyArgs };
